table Table
	lineageTag: 7bce122b-e3ae-472d-9ecc-c01a84b52ec0

	column 'User ID'
		dataType: string
		lineageTag: b005eb8f-dc5d-472a-ade4-eb69be1d5ba8
		summarizeBy: none
		sourceColumn: User ID

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 8fb3f9b5-366b-4d3b-9501-cb443c6014bc
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 48f72982-645f-4cca-a41d-bd0464d2e3e9
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wyk0qLc4sSk1JqTQwN7CIT89NzMzRS87PVXaNCFF2SMpMLMksyClPKk8tTSrQy8/LzUwuyi/OTysBqVHSUXKC6QayDZVidaKVDC3NLA0dDUwczeJzM0uK9RKT9TLziDTNNzEvP0vBuzQ3sQjIM1KKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"User ID" = _t, name = _t, ID = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"User ID", type text}, {"name", type text}, {"ID", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","19691A04A6_mits.ac.in#EXT#@biatiplwbweubp.onmicrosoft.com","19691A04A6@mits.ac.in",Replacer.ReplaceText,{"User ID"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","mbusireddy0708_gmail.com#EXT#@biatiplwbweubp.onmicrosoft.com","live.com#mbusireddy0708@gmail.com",Replacer.ReplaceText,{"User ID"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

